version: 2

models:
  - name: dim_customer
    description: "Dimension table for customers."
    columns:
      - name: customer_id
        description: "Primary key of the customer."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customer."
      - name: last_name
        description: "Last name of the customer."
      - name: company
        description: "Company of the customer."
      - name: address
        description: "Address of the customer."
      - name: city
        description: "City of the customer."
      - name: state
        description: "State of the customer."
      - name: country
        description: "Country of the customer."
      - name: postal_code
        description: "Postal code of the customer."
      - name: phone
        description: "Phone number of the customer."
      - name: fax
        description: "Fax number of the customer."
      - name: email
        description: "Email address of the customer."
      - name: support_rep_id
        description: "Foreign key to the employee table (support representative)."
      - name: first_order_date
        description: "Date of the customer's first order."
      - name: most_recent_order_date
        description: "Date of the customer's most recent order."
      - name: number_of_orders
        description: "Total number of orders placed by the customer."
      - name: lifetime_value
        description: "Total lifetime value of the customer."

  - name: dim_employee
    description: "Dimension table for employees."
    columns:
      - name: employee_id
        description: "Primary key of the employee."
        tests:
          - unique
          - not_null
      - name: last_name
        description: "Last name of the employee."
      - name: first_name
        description: "First name of the employee."
      - name: title
        description: "Job title of the employee."
      - name: reports_to
        description: "Manager's employee ID."
      - name: birth_date
        description: "Birth date of the employee."
      - name: hire_date
        description: "Hire date of the employee."
      - name: address
        description: "Address of the employee."
      - name: city
        description: "City of the employee."
      - name: state
        description: "State of the employee."
      - name: country
        description: "Country of the employee."
      - name: postal_code
        description: "Postal code of the employee."
      - name: phone
        description: "Phone number of the employee."
      - name: fax
        description: "Fax number of the employee."
      - name: email
        description: "Email address of the employee."

  - name: dim_tracks
    description: "Dimension table for tracks."
    columns:
      - name: track_id
        description: "Primary key of the track."
        tests:
          - unique
          - not_null
      - name: track_name
        description: "Name of the track."
      - name: album_title
        description: "Title of the album."
      - name: artist_name
        description: "Name of the artist."
      - name: genre_name
        description: "Name of the genre."
      - name: media_type_name
        description: "Name of the media type."
      - name: composer
        description: "Composer of the track."
      - name: milliseconds
        description: "Duration of the track in milliseconds."
      - name: bytes
        description: "Size of the track in bytes."
      - name: unit_price
        description: "Unit price of the track."

  - name: fct_sales
    description: "Fact table for sales transactions."
    columns:
      - name: invoice_line_id
        description: "Primary key of the sales fact."
        tests:
          - unique
          - not_null
      - name: invoice_id
        description: "Foreign key to the invoice table."
      - name: track_id
        description: "Foreign key to the track table."
      - name: customer_id
        description: "Foreign key to the customer table."
      - name: invoice_date
        description: "Date of the invoice."
      - name: quantity
        description: "Quantity of the track sold."
      - name: unit_price
        description: "Unit price of the track."
      - name: total_amount
        description: "Total amount for the line item."
