version: 2

models:
  - name: int_customers_orders
    description: "Intermediate model aggregating orders by customer."
    columns:
      - name: customer_id
        description: "Primary key of the customer."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customer."
      - name: last_name
        description: "Last name of the customer."
      - name: first_order_date
        description: "Date of the customer's first order."
      - name: most_recent_order_date
        description: "Date of the customer's most recent order."
      - name: number_of_orders
        description: "Total number of orders placed by the customer."
      - name: total_order_amount
        description: "Total value of all orders placed by the customer."

  - name: int_sales
    description: "Intermediate model for sales data."
    columns:
      - name: invoice_line_id
        description: "Primary key of the invoice line."
        tests:
          - unique
          - not_null
      - name: invoice_id
        description: "Foreign key to the invoice table."
      - name: track_id
        description: "Foreign key to the track table."
      - name: unit_price
        description: "Unit price of the track."
      - name: quantity
        description: "Quantity of the track."
      - name: total
        description: "Total amount for the line item."
      - name: invoice_date
        description: "Date of the invoice."
      - name: customer_id
        description: "Foreign key to the customer table."

  - name: int_tracks
    description: "Intermediate model for tracks data joined with album, artist, genre, and media type."
    columns:
      - name: track_id
        description: "Primary key of the track."
        tests:
          - unique
          - not_null
      - name: track_name
        description: "Name of the track."
      - name: album_title
        description: "Title of the album."
      - name: artist_name
        description: "Name of the artist."
      - name: genre_name
        description: "Name of the genre."
      - name: media_type_name
        description: "Name of the media type."
      - name: composer
        description: "Composer of the track."
      - name: milliseconds
        description: "Duration of the track in milliseconds."
      - name: bytes
        description: "Size of the track in bytes."
      - name: unit_price
        description: "Unit price of the track."
